name: Build LLVM (Linux)
run-name: Build LLVM for r${{inputs.version}}${{inputs.revision}} ${{inputs.projects}}
on:
  workflow_dispatch:
    inputs:
      version:
        description: "NDK Release version:"
        default: "30"
        required: true
      revision:
        description: "NDK Release revision:"
        required: false
        type: string
      projects:
        description: "Projects to build:"
        # bolt;clang;clang-tools-extra;compiler-rt;cross-project-tests;libc;libclc;lld;lldb;mlir;openmp;polly;pstl;flang
        default: "bolt;clang;clang-tools-extra;lld"
        required: true

permissions:
  contents: write
  packages: read

jobs:
  build:
    uses: ./.github/workflows/build-llvm.yml
    secrets: inherit
    with:
      platform: linux
      version: ${{ inputs.version }}
      revision: ${{ inputs.revision }}
      projects: ${{ inputs.projects }}
      # x86_64-linux-gnux32
      targets: >-
        ["aarch64-linux-musl", "aarch64-linux-gnu", "aarch64_be-linux-gnu",
         "arm-linux-gnueabi", "arm-linux-musleabihf", "arm-linux-gnueabihf",
         "armeb-linux-gnueabi", "armeb-linux-gnueabihf", "hexagon-linux-musl",
         "loongarch64-linux-gnu", "loongarch64-linux-muslf32", "loongarch64-linux-gnusf",
         "mips-linux-gnueabi", "mips-linux-gnueabihf", "mips64-linux-gnuabin32",
         "mips64-linux-gnuabi64", "mips64el-linux-gnuabin32", "mips64el-linux-gnuabi64",
         "mipsel-linux-gnueabi", "mipsel-linux-gnueabihf", "powerpc-linux-musleabi",
         "powerpc-linux-musleabihf", "powerpc64-linux-musl", "powerpc64le-linux-gnu",
         "riscv32-linux-gnu", "riscv64-linux-gnu", "s390x-linux-gnu",
         "thumb-linux-musleabi", "thumb-linux-musleabihf", "thumbeb-linux-musleabi",
         "thumbeb-linux-musleabihf", "x86-linux-musl", "x86-linux-gnu",
         "x86_64-linux-musl", "x86_64-linux-gnu"]
