name: Build LLVM (Bionic)
run-name: Build LLVM for r${{inputs.version}}${{inputs.revision}} ${{inputs.projects}}
on:
  workflow_dispatch:
    inputs:
      version:
        description: "NDK Release version:"
        default: "30"
        required: true
      revision:
        description: "NDK Release revision:"
        required: false
        type: string
      projects:
        description: "Projects to build:"
        default: "bolt;clang;clang-tools-extra;lld"
        required: true

jobs:
  build:
    uses: ./.github/workflows/build-llvm.yml
    secrets: inherit
    with:
      platform: bionic
      version: ${{ inputs.version }}
      revision: ${{ inputs.revision }}
      projects: ${{ inputs.projects }}
      targets: '["aarch64-linux-android", "armv7a-linux-androideabi", "i686-linux-android", "x86_64-linux-android"]'
